# 以下为站点信息
site_name: 东北师大附中生存手册
site_url: https://ziyou-qinghua.github.io/

# 以下为仓库信息
repo_url: https://github.com/ziyou-qinghua/ziyou-qinghua.github.io/
repo_name: ziyou-qinghua/ziyou-qinghua.github.io/

# 以下为版权信息
copyright: '<p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"> Copyright &copy; 东北师大附中生存手册众编写人员. Some rights reserved: <a property="dct:title" rel="cc:attributionURL" href="https://ziyou-qinghua.github.io">东北师大附中生存手册</a> is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p>'

theme:
  language: zh
  name: material # 设定主题为 material
  custom_dir: overrides # 启用评论需要此行
  palette: #日夜模式切换
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple #基调色
      accent: green #强调色
      toggle:
        icon: material/weather-sunny
        name: 日间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple #基调色
      accent: red #强调色
      toggle:
        icon: material/weather-night
        name: 夜间模式
  icon:
    repo: fontawesome/brands/github # 设置git仓库图标
    admonition: # 注释图标
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  
  features:
    - content.code.copy # 启用代码块复制按钮，尽管我觉得用不上
    - navigation.tabs # 页顶导航栏
    - navigation.tabs.sticky # 粘性导航栏
    - toc.follow # 边栏自动滚动
    - navigation.top # 回到顶部
    - navigation.footer # 启用页尾上一页下一页按钮
    - navigation.instant # 内部链接即时加载

markdown_extensions: # markdown扩展插件
  - pymdownx.arithmatex: # 数学公式支持
      generic: true
  - pymdownx.caret # 下划线与上标
  - pymdownx.mark # 强调
  - pymdownx.tilde # 删除线与下标
  - admonition # 启用警告语法扩展
  - pymdownx.details # 启用警告语法扩展
  - pymdownx.superfences # 启用警告语法扩展

extra_css: #js文件
  - css/heimu.css # 黑幕功能实现

extra_javascript: #js文件
  - javascripts/mathjax.js # 数学公式支持
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # 数学公式支持

# 以下为目录信息
nav:
  - "index.md"
  - 前言:
      - "intro/docs.md"
      - "intro/notice.md"
      - "intro/contribution.md"
      - "intro/thanks.md"
  - 日程安排:
      - "time/daily.md"
      - "time/break.md"
      - "time/lessons.md"
      - "time/entertainment.md"
      - "time/extra-course.md"
  - 分班及班型:
      - "type/exam.md"
      - "type/num.md"
      - "type/gaokao.md"
      - "type/honor.md"
  - 学校简介:
      - "school/uniform.md"
      - "school/ziyou.md"
      - "school/qinghua.md"
  # - 校外地图:
  - 硬件设备:
      - "device/classroom.md"
  - 学生团体:
      - "team/orgnization.md"
      - "team/club.md"
      - "team/unofficial.md"
  - 杂项:
      - "others.md"
  - 贡献:
      - "conrtibutiion/how.md"
      - "conrtibutiion/extra-grammar.md"
  - "board.md"
