site_name: 东北师大附中生存手册
site_url: https://ziyou-qinghua.github.io/site/
theme:
  name: material
  custom_dir: overrides

nav:
  - "index.md"

  - 时间:
      - "daily.md"
  - 班型:
      - "class-exam.md"
      - "class-num.md"
      - "class-gaokao.md"